INSERT INTO LOCATION VALUES(8001, 'Malabe');
INSERT INTO LOCATION VALUES(8002, 'Matara');
INSERT INTO LOCATION VALUES(8003, 'Galle');
INSERT INTO LOCATION VALUES(8004, 'Colombo');
INSERT INTO LOCATION VALUES(8005, 'Kandy');
